name: Push-to-EC2 instance

on:
  push:
    branches:
        - main
jobs:
  deploy:
   name: Push to EC2
   runs-on: ubuntu-latest
   steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.0	
      with:
       host: ec2-65-0-6-242.ap-south-1.compute.amazonaws.com
       username: ubuntu
       key: ${{ secrets.EC2_SSH_KEY }}
       port: 22
       script: |
          ls
          cd practice-cicd
          git pull origin main
          export PATH=/home/ubuntu/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install && pm2 restart fe-server