name: Push-to-EC2 instance

on:
  push:
    branches:
        - main
jobs:
      deploy:
        name: Push to EC2
        runs-on: ubuntu-latest
        steps:
         - name: Checkout the code
         uses: actions/checkout@v2
         - name: executing remote ssh commands using password
         uses: appleboy/ssh-action@v1.2.0	
         with:
         host: 13.127.14.79
         usernane: ubuntu
         key: ${{secrets.EC2_SSH_KEY}}
         port: 22
         script: |
          ls


          